apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: pcejks/jkspce:51 # 例如：index.docker.io/your-username/your-image:latest
        ports:
        - containerPort: 80
        